name: diploma_verification
description: Diploma verification mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  
  # QR scanning
  mobile_scanner: ^5.0.0
  
  # File picking
  file_picker: ^8.0.0

  # File sharing
  receive_sharing_intent: ^1.8.1
  
  # Permissions
  permission_handler: ^11.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" 
  min_sdk_android: 21